jdbc:
  driver: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/shop?useUnicode=true&characterEncoding=utf8
  username: root
  password: root
  maxPoolSize: 100
  minPoolSize: 10
  initPoolSize: 10
  minEvictableIdleTimeMillis: 300000
  autoCommitOnClose: false
  timeout: 1000
  try: 2
  filter: stat
redis:
  host: localhost
  port: 6379
  password: XuJun2230
  timeout: 3600
  max-idle: 8
  min-idle: 1
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.dream.login.entity
spring:
  redis:
    timeout: ${redis.timeout}
    host: ${redis.host}
    port: ${redis.port}
    jedis:
      pool:
        max-idle: ${redis.max-idle}
        min-idle: ${redis.min-idle}
    password: ${redis.password}
  application:
    name: shop-login
server:
  port: 10051
dubbo:
  application:
    id: dubbo-provider-demo
    name: dubbo-provider-demo
  protocol:
    id: login
    name: login
    port: 123456
  registry:
    id: login-registory
    address: zookeeper://127.0.0.1:2181



